export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const ADD_NEW_PATIENT_BEGIN = "ADD_NEW_PATIENT_BEGIN";
export const ADD_NEW_PATIENT_ERROR = "ADD_NEW_PATIENT_ERROR";
export const ADD_NEW_PATIENT_SUCCESS = "ADD_NEW_PATIENT_SUCCESS";

export const GET_MY_PATIENTS_BEGIN = "GET_MY_PATIENTS_BEGIN";
export const GET_MY_PATIENTS_SUCCESS = "GET_MY_PATIENTS_SUCCESS";

export const DELETE_MY_PATIENT = "DELETE_MY_PATIENT";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
